"""Produce the signing fixture from the Python implementation, and check the C++ side against it.

RSA-PSS salts randomly, so `KalshiRequestSigner.sign` called twice over one message with one key
returns two different signatures and neither is the expected value of the other. The check that
replaces a byte comparison runs in both directions, and this script is both of them.

Python to C++, committed and gated by `tests/test_signer.cpp` on every run:

    uv run python tests/golden/generate_signing_fixture.py --infra ../prediction-market-infra

generates a throwaway RSA-2048 key, signs a fixed set of requests with the real
`auth/signer.py`, and writes the public key and the signatures under `signing/`. The private half
never leaves the temporary directory it was made in, so nothing here is a key a scanner has to
decide about.

C++ to Python, run deliberately, since gating it would put `cryptography` on all three CI runners
to verify a value that is different every run:

    uv run python tests/golden/generate_signing_fixture.py --verify-cpp build/dev/signer_cross_check

reads what `tests/test_signer.cpp` wrote on its last run and verifies each signature with
`cryptography`'s own PSS verifier at the published parameters. `signing/SOURCE.txt` records when
that last passed.
"""

from __future__ import annotations

import argparse
import base64
import importlib.util
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path
from types import ModuleType

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

# The three from `tests/auth/test_signer.py`, the request `benchmarks/latency_bench.py` times, and
# one DELETE so a path with an id in it is covered.
REQUESTS = [
    ("1703123456789", "GET", "/trade-api/v2/portfolio/orders"),
    ("1703123456789", "POST", "/trade-api/v2/portfolio/orders"),
    ("1703123456789", "GET", "/trade-api/ws/v2"),
    ("1756512000000", "GET", "/trade-api/v2/portfolio/balance"),
    ("1756512000000", "DELETE", "/trade-api/v2/portfolio/orders/9f2c1e7a4b6d"),
]

PSS = padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.DIGEST_LENGTH)

_CROSS_CHECK_LINE = "The C++ signatures were last verified here with --verify-cpp: "


def load_signer(infra_root: Path) -> ModuleType:
    """Import `kalshi_bot.auth.signer` out of a checkout without installing the package."""
    path = infra_root / "src" / "kalshi_bot" / "auth" / "signer.py"
    spec = importlib.util.spec_from_file_location("kalshi_bot_auth_signer", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def git_head(root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True, check=False
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def generate(infra_root: Path, out_dir: Path) -> None:
    signer_module = load_signer(infra_root)
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

    with tempfile.TemporaryDirectory() as tmp:
        key_path = Path(tmp) / "fixture_key.pem"
        key_path.write_bytes(
            private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )
        signer = signer_module.KalshiRequestSigner(key_path)
        rows = []
        for timestamp, method, path in REQUESTS:
            if path == signer_module._WS_AUTH_PATH:
                signature = signer.sign_websocket_auth(timestamp)
            else:
                signature = signer.sign(timestamp, method, path)
            private_key.public_key().verify(
                base64.b64decode(signature), f"{timestamp}{method}{path}".encode(), PSS,
                hashes.SHA256(),
            )
            rows.append(f"{timestamp}\t{method}\t{path}\t{signature}")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "public_key.pem").write_bytes(
        private_key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
    )
    (out_dir / "vectors.tsv").write_text("\n".join(rows) + "\n")

    import cryptography

    (out_dir / "SOURCE.txt").write_text(
        "Generated by generate_signing_fixture.py. Do not edit by hand.\n"
        "\n"
        f"date: {date.today().isoformat()}\n"
        f"prediction-market-infra: {git_head(infra_root)}\n"
        f"cryptography: {cryptography.__version__}\n"
        f"python: {sys.version.split()[0]}\n"
        f"key: RSA-2048, generated for this fixture and discarded\n"
        f"vectors: {len(rows)}\n"
        "\n"
        f"{_CROSS_CHECK_LINE}not yet\n"
    )
    print(f"wrote {len(rows)} vectors and the public key to {out_dir}")


def verify_cpp(check_dir: Path) -> None:
    public_key = serialization.load_pem_public_key((check_dir / "cpp_public_key.pem").read_bytes())
    if not isinstance(public_key, rsa.RSAPublicKey):
        raise SystemExit(f"{check_dir}/cpp_public_key.pem is not an RSA public key")

    lines = (check_dir / "cpp_signatures.tsv").read_text().splitlines()
    for line in lines:
        message, signature = line.split("\t")
        try:
            public_key.verify(base64.b64decode(signature), message.encode(), PSS, hashes.SHA256())
        except InvalidSignature:
            raise SystemExit(f"the C++ signature over {message!r} does not verify here") from None
    print(f"{len(lines)} C++ signatures verified against the Python's own PSS parameters")
    record_cross_check(len(lines))


def record_cross_check(count: int) -> None:
    """Date the fixture's own record of the direction that is not gated in CI."""
    source = Path(__file__).parent / "signing" / "SOURCE.txt"
    lines = [
        f"{_CROSS_CHECK_LINE}{date.today().isoformat()}, {count} signatures"
        if line.startswith(_CROSS_CHECK_LINE)
        else line
        for line in source.read_text().splitlines()
    ]
    source.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--infra", type=Path, help="a prediction-market-infra checkout")
    parser.add_argument("--out", type=Path, default=Path(__file__).parent / "signing")
    parser.add_argument("--verify-cpp", type=Path, help="the directory tests/test_signer.cpp wrote")
    args = parser.parse_args()

    if args.verify_cpp is not None:
        verify_cpp(args.verify_cpp)
        return
    if args.infra is None:
        raise SystemExit("--infra or --verify-cpp")
    generate(args.infra, args.out)


if __name__ == "__main__":
    main()
